# Generated by Django 4.1.7 on 2023-04-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebookapp', '0002_lecturer_classes_semester_semester_semester_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
    ]
