# Generated by Django 4.1.7 on 2023-04-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebookapp', '0003_remove_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_class',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='classes',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
