# Generated by Django 4.1.7 on 2023-04-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebookapp', '0004_remove_course_semesters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('semesters', models.ManyToManyField(blank=True, to='gradebookapp.semester')),
            ],
        ),
    ]
