# Generated by Django 4.1.7 on 2023-04-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebookapp', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffId', models.IntegerField(default=0)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('course', models.ManyToManyField(related_name='courses', to='gradebookapp.course')),
            ],
        ),
    ]
