# Generated by Django 4.1.7 on 2023-04-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebookapp', '0006_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('number', models.IntegerField(default=1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebookapp.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebookapp.lecturer')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebookapp.semester')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='classes',
            field=models.ManyToManyField(related_name='lecturers', to='gradebookapp.class'),
        ),
    ]
