# Generated by Django 4.1.7 on 2023-04-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebookapp', '0010_studentenrollment_delete_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='classId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='studentId',
            field=models.IntegerField(default=0),
        ),
    ]
